unit uPSI_PythonGUIInputOutput;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 

 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TPSImport_PythonGUIInputOutput = class(TPSPlugin)
  public
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_TPythonGUIInputOutput(CL: TPSPascalCompiler);
procedure SIRegister_PythonGUIInputOutput(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_PythonGUIInputOutput_Routines(S: TPSExec);
procedure RIRegister_TPythonGUIInputOutput(CL: TPSRuntimeClassImporter);
procedure RIRegister_PythonGUIInputOutput(CL: TPSRuntimeClassImporter);

procedure Register;

implementation


uses
   Windows
  ,Messages
  ,Graphics
  ,Controls
  ,Forms
  ,Dialogs
  ,StdCtrls
  ,PythonEngine
  ,PythonGUIInputOutput
  ;
 
 
procedure Register;
begin
  RegisterComponents('Pascal Script', [TPSImport_PythonGUIInputOutput]);
end;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_TPythonGUIInputOutput(CL: TPSPascalCompiler);
begin
  //with RegClassS(CL,'TPythonInputOutput', 'TPythonGUIInputOutput') do
  with CL.AddClassN(CL.FindClass('TPythonInputOutput'),'TPythonGUIInputOutput') do
  begin
    RegisterMethod('Constructor Create( AOwner : TComponent)');
    RegisterMethod('Procedure DisplayString( const str : string)');
    RegisterProperty('Output', 'TCustomMemo', iptrw);
  end;
end;

(*----------------------------------------------------------------------------*)
procedure SIRegister_PythonGUIInputOutput(CL: TPSPascalCompiler);
begin
 CL.AddConstantN('WM_WriteOutput','LongInt').SetInt( WM_USER + 1);
  SIRegister_TPythonGUIInputOutput(CL);
 CL.AddDelphiFunction('Procedure Register');
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure TPythonGUIInputOutputOutput_W(Self: TPythonGUIInputOutput; const T: TCustomMemo);
begin Self.Output := T; end;

(*----------------------------------------------------------------------------*)
procedure TPythonGUIInputOutputOutput_R(Self: TPythonGUIInputOutput; var T: TCustomMemo);
begin T := Self.Output; end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_PythonGUIInputOutput_Routines(S: TPSExec);
begin
 S.RegisterDelphiFunction(@Register, 'Register', cdRegister);
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_TPythonGUIInputOutput(CL: TPSRuntimeClassImporter);
begin
  with CL.Add(TPythonGUIInputOutput) do
  begin
    RegisterConstructor(@TPythonGUIInputOutput.Create, 'Create');
    RegisterMethod(@TPythonGUIInputOutput.DisplayString, 'DisplayString');
    RegisterPropertyHelper(@TPythonGUIInputOutputOutput_R,@TPythonGUIInputOutputOutput_W,'Output');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_PythonGUIInputOutput(CL: TPSRuntimeClassImporter);
begin
  RIRegister_TPythonGUIInputOutput(CL);
end;

 
 
{ TPSImport_PythonGUIInputOutput }
(*----------------------------------------------------------------------------*)
procedure TPSImport_PythonGUIInputOutput.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_PythonGUIInputOutput(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_PythonGUIInputOutput.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  RIRegister_PythonGUIInputOutput(ri);
  RIRegister_PythonGUIInputOutput_Routines(CompExec.Exec); // comment it if no routines
end;
(*----------------------------------------------------------------------------*)
 
 
end.
